spring:
   datasource:
      url: jdbc:mysql://localhost:3306/testbatch?useSSL=false
      username: root
      password: 
   jpa:
      generate-ddl: true
      show-sql: true
   hibernate:
      ddl-auto: create-drop
   properties:
      hibernate:
         dialect: org.hibernate.dialect.MySQL5Dialect
   batch:
      initialize-schema: always
      job:
         enabled: false